Update aurora\

diff --git a/aurora b/aurora
--- a/aurora
+++ b/aurora
@@ -237,11 +237,36 @@ case "$1" in
         fi
         ;;
         reinstall)
-        bash <(curl -s "https://raw.githubusercontent.com/shadowed1/Aurora/main/aurora_installer.sh?$(date +%s)")
+        bash <(curl -s "https://raw.githubusercontent.com/shadowed1/Aurora/beta/aurora_installer.sh?$(date +%s)")
         ;;
         uninstall)
         aurora_uninstall
         ;;
+         version)
+            if [[ -f "$VERSION_FILE" ]]; then
+            CURRENT_VER=$(cat "$HOME/opt/bin/version")
+            CURRENT_VER_NO=$(echo "$CURRENT_VER" | sed -e 's/VERSION=//' -e 's/"//g' -e 's/\.//g')
+        
+            LATEST_VER=$(curl -Ls https://raw.githubusercontent.com/shadowed1/Aurora/refs/heads/beta/version)
+            LATEST_VER_NO=$(echo "$LATEST_VER" | sed -e 's/VERSION=//' -e 's/"//g' -e 's/\.//g')
+        
+            if [[ "$CURRENT_VER_NO" -lt "$LATEST_VER_NO" ]]; then
+                echo "${CYAN}You're using $CURRENT_VER which is NOT the latest version.${RESET}"
+                read -rp "Would you like to 'reinstall' to get $LATEST_VER ? (Y/n): " choice
+                if [[ "$choice" =~ ^[Yy]$ ]]; then
+                    echo "${CYAN}Reinstalling!${RESET}"
+                    bash <(curl -s "https://raw.githubusercontent.com/shadowed1/Aurora/beta/aurora_installer.sh?$(date +%s)")
+                else
+                    echo "${YELLOW}Skipping reinstall.${RESET}"
+                fi
+            else
+                echo "${GREEN}You're using $CURRENT_VER which is up-to-date, so you're good.${RESET}"
+            fi
+        else
+            echo "${RED}Version file not found.${RESET}"
+            exit 1
+        fi
+    ;;
     *)
         echo "${RED}Unknown command $1 ${RESET}"
         show_help
